image: alpine:latest

services:
  - docker:dind

stages:
  - build
  - tests
  
SourceGuard:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft -D sourceguard --src ./

Iac-Assessment:
  stage: tests
  image: checkpoint/shiftleft:staging
  script:
    - shiftleft -D iac-assessment -p ./terraform-template -r -64 -s critical

DockerBuild:
  stage: build
  image: docker:latest
  before_script:
    - echo "do not inherit before_script"
  artifacts:
    expire_in: 7 days
    paths:
      - release
  script:
    - docker build -t checkpoint/demo-app:latest .
    - mkdir release 
    - docker save checkpoint/demo-app:latest -o release/demo-app-image.tar
