image: alpine:latest

stages:
  - tests
  
SourceGuard:
  stage: tests
  image: sourceguard/sourceguard-cli:latest
  script:
    - /sourceguard-cli -V
    - echo "Demo X"
    - /sourceguard-cli --src ./ -x "src/nodejs/node_modules/**" -x test.sh
