image: alpine:latest

services:
  - docker:dind

stages:
  - security-tests
  
sourceguard:
  stage: security-tests
  image: sgdemo/demo-app:latest  
  script:    
    - /usr/local/demo-app/sourceguard-cli --src ./ -x "test.sh"