image: alpine:latest

stages:
  - tests
  
sourceguard:
  stage: tests
  image: sourceguard/sourceguard-cli:latest
  script:
    - /sourceguard-cli --src ./ -x "test.sh" -x "src/**"
    - ls -al .git/
    - cat .git/FETCH_HEAD