image: alpine:latest

services:
  - docker:dind
  
stages:
  - security-tests

  
sourceguard:
  stage: security-tests
  image: sourceguard/sourceguard-cli:latest
  script:    
    - /sourceguard-cli --src ./ -x "test.sh"