image: alpine:latest

services:
  - docker:dind

stages:
  - build
  - tests
  
SourceGuard:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft -D sourceguard -s ./

Iac-Assessment:
  stage: tests
  image: checkpoint/shiftleft:staging
  script:
    - shiftleft -D iac-assessment -p ./terraform-template -r -64 -s medium

Image-Scan:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft -D sourceguard -i release/demo-app-image.tar 

DockerBuild:
  stage: build
  image: docker:latest
  before_script:
    - echo "do not inherit before_script"
  artifacts:
    expire_in: 2 hours
    paths:
      - release
  script:
    - docker build -t checkpoint/demo-app:latest .
    - mkdir release 
    - docker save checkpoint/demo-app:latest -o release/demo-app-image.tar
