image: alpine:latest

services:
  - docker:dind

stages:
  - build

DockerBuild:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 2 hours
    paths:
      - release
  script:
    - docker build -t checkpoint/demo-app:latest .
    - mkdir release 
    - docker save checkpoint/demo-app:latest -o release/demo-app-image.tar
