image: alpine:latest

stages:
  - tests
  
sourceguard:
  stage: tests
  image: sourceguard/sourceguard-cli:latest
  script:
    - cat .git/ORIG_HEAD
    - /sourceguard-cli --src ./ -x "test.sh" -x "src/**"   