image: alpine:latest

stages:
  - tests
  
sourceguard:
  stage: tests
  image: sourceguard/sourceguard-cli:latest
  script:
    - /sourceguard-cli -V
    - /sourceguard-cli -h
    - /sourceguard-cli --src ./ -x "test.sh"