image: alpine:latest

services:
  - docker:dind

stages:
  - tests
  - build
  - pre-deploy
  
  
SourceGuard:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft sourceguard -s ./

Iac-Assessment:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft -D iac-assessment -p ./terraform-template -r -64 -s critical

Image-Scan:
  stage: pre-deploy
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft sourceguard -i release/demo-app-image.tar

DockerBuild:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 2 hours
    paths:
      - release
  script:
    - docker build -t checkpoint/demo-app:latest .
    - mkdir release 
    - docker save checkpoint/demo-app:latest -o release/demo-app-image.tar
