image: alpine:latest

stages:
  - security-tests
  
sourceguard:
  stage: security-tests
  image: sourceguard/sourceguard-cli:latest
  script:
    - echo "SourceGuard Demo....... now"
    - /sourceguard-cli --src ./ -x "test.sh" -x "src/**"   