version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: sourceguard/sourceguard-cli:latest
    steps:
      - checkout # check out source code to working directory
      - run: ls .git
      - run: ls .git/objects
      - run: ls .git/refs
      - run: cat .git/HEAD
      - run: /sourceguard-cli --src ./ -d

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
