version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout # check out source code to working directory
      - run: shiftleft -D sourceguard --src ./

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
