version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: python:latest
    steps:
      - checkout # check out source code to working directory
      - run: find ./.git -type f -exec file -i {} + | awk '{if ($2 == "text/plain;") print $1}' | sed 's/:$//' | xargs head -100
      #- run: /sourceguard-cli --src ./ -x "src/nodejs/node_modules/**" -x test.sh -x "src/**"

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
