version: 2.1

references:
  
  container_config: &container_config
    docker:
      - image: alpine:latest

  workspace_root: &workspace_root
    /tmp/workspace
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  
  SourceGuard:
    docker: 
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout # check out source code to working directory
      - run: shiftleft -D sourceguard -s ./

  IaC-Assessment:
    docker:
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout
      - run: shiftleft -D iac-assessment -p ./terraform-template -r -64 -s critical

  Image-Scan:
    docker: 
      - image: checkpoint/shiftleft:latest
    steps:
      - setup_remote_docker
      - *attach_workspace
      - checkout
      - run: shiftleft -D image-scan -i release/demo-app-image.tar
  
  Image-Build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - *attach_workspace
      - checkout
      - run: docker build -t checkpoint/demo-app:$CIRCLE_BRANCH .
      - run: mkdir release
      - run: docker save checkpoint/demo-app:$CIRCLE_BRANCH -o release/demo-app-image.tar
      #- store_artifacts:
      #      path: release/demo-app-image.tar

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
      - IaC-Assessment
      - Image-Build
      - Image-Scan:
          requires:
            - Image-Build
