version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout # check out source code to working directory
      - run: shiftleft -D sourceguard --src ./

  IaC-Assessment:
    docker:
      - image: checkpoint/shiftleft:staging
    steps:
      - checkout # check out source code to working directory
      - run: shiftleft -D iac-assessment -p ./terraform-template -r -64

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
      - IaC-Assessment
