version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: sourceguard/sourceguard-cli:latest
    steps:
      - run: /sourceguard-cli --src ./ -x "src/nodejs/node_modules/**" -d

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard
